### ISSUE TITLE
4 Misnamed Textures

### ISSUE THREAD

**Issue by Napiophelios** [vlapsley/australia#1]
Some where in the code (craftitems maybe?)
these textures are using the wrong name;
australia_ferntuber.png
australia_ferntuber_roasted.png
australia_fiddlehead.png
australia_fiddlehead_roasted.png

instead of:
aus_ferntuber.png
aus_ferntuber_roasted.png
aus_fiddlehead.png
aus_fiddlehead_roasted.png

**Comment by vlapsley** [comment]
Fixed in latest version 0.3.1, see this [diff](https://github.com/vlapsley/australia/commit/c22c8e8130a51fb15833fb56045d07250367a237#diff-55abe9afc3185ea3def59718d5cea6c3)

Thanks, mate!
